version: 2

updates:
  - package-ecosystem: "maven"
    directory: "/"

    schedule:
      interval: "daily"

    open-pull-requests-limit: 5

    labels:
      - "dependencies"
      - "dependabot"

    commit-message:
      prefix: "deps"

    groups:
      spring:
        patterns:
          - "org.springframework*"

      test:
        patterns:
          - "org.junit*"
          - "org.mockito*"

      other:
        patterns:
          - "*"